# Generated by Django 4.2.11 on 2024-04-26 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shift_manager_app', '0001_initial'),
        ('csv_generator_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrequestmodel',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_manager_app.member'),
        ),
    ]
